In [88]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Вариант
3 в списке

N = 3

Вариант 24

Оптимизационный критерий Максимакс

In [89]:
N = 3
low = 1/(N+1)
high = N+1

payoff = np.random.uniform(low=low, high=high, size=(10, 10))
print(payoff.round(3))


[[1.466 3.464 1.625 2.903 3.342 1.309 3.356 1.075 0.62  3.232]
 [2.92  0.608 3.057 1.522 3.719 1.345 1.808 0.458 0.668 1.588]
 [3.806 2.901 0.903 3.554 0.308 3.02  2.272 0.466 2.694 1.108]
 [0.561 1.188 1.838 3.92  0.389 1.892 2.057 1.341 0.596 2.277]
 [1.098 1.515 2.295 0.339 0.906 2.797 2.625 3.208 1.829 2.953]
 [1.085 3.87  1.581 0.674 1.738 1.922 1.288 1.109 0.447 0.788]
 [1.64  2.121 3.93  0.601 1.604 1.854 3.823 0.804 1.109 3.437]
 [1.754 2.7   2.472 1.94  3.358 3.898 0.919 1.042 2.553 1.207]
 [2.965 1.527 3.944 0.885 1.218 1.015 2.893 1.072 2.44  1.455]
 [3.817 3.518 1.612 2.762 2.891 3.003 0.433 0.709 2.557 3.988]]


In [90]:
p = np.random.uniform(size=10)
p /= p.sum()

print(p.round(3))

[0.119 0.032 0.129 0.122 0.115 0.121 0.092 0.095 0.033 0.143]


In [91]:
pd.DataFrame(data=payoff, columns=p.round(3)).round(3)

0.119  0.032  0.129  0.122  0.115  0.121  0.092  0.095  0.033  0.143
0  1.466  3.464  1.625  2.903  3.342  1.309  3.356  1.075  0.620  3.232
1  2.920  0.608  3.057  1.522  3.719  1.345  1.808  0.458  0.668  1.588
2  3.806  2.901  0.903  3.554  0.308  3.020  2.272  0.466  2.694  1.108
3  0.561  1.188  1.838  3.920  0.389  1.892  2.057  1.341  0.596  2.277
4  1.098  1.515  2.295  0.339  0.906  2.797  2.625  3.208  1.829  2.953
5  1.085  3.870  1.581  0.674  1.738  1.922  1.288  1.109  0.447  0.788
6  1.640  2.121  3.930  0.601  1.604  1.854  3.823  0.804  1.109  3.437
7  1.754  2.700  2.472  1.940  3.358  3.898  0.919  1.042  2.553  1.207
8  2.965  1.527  3.944  0.885  1.218  1.015  2.893  1.072  2.440  1.455
9  3.817  3.518  1.612  2.762  2.891  3.003  0.433  0.709  2.557  3.988

In [92]:
maxes = np.apply_along_axis(np.max, 1, payoff)
print(maxes.round(3).reshape(10, 1))

[[3.464]
 [3.719]
 [3.806]
 [3.92 ]
 [3.208]
 [3.87 ]
 [3.93 ]
 [3.898]
 [3.944]
 [3.988]]


In [93]:
print(
    pd.DataFrame(
        data=np.hstack((payoff, maxes.reshape((10, 1)))),
        columns=p.round(3).tolist() + ["max"]
    ).round(3).to_latex()
)

\begin{tabular}{lrrrrrrrrrrr}
\toprule
{} &  0.119 &  0.032 &  0.129 &  0.122 &  0.115 &  0.121 &  0.092 &  0.095 &  0.033 &  0.143 &    max \\
\midrule
0 &  1.466 &  3.464 &  1.625 &  2.903 &  3.342 &  1.309 &  3.356 &  1.075 &  0.620 &  3.232 &  3.464 \\
1 &  2.920 &  0.608 &  3.057 &  1.522 &  3.719 &  1.345 &  1.808 &  0.458 &  0.668 &  1.588 &  3.719 \\
2 &  3.806 &  2.901 &  0.903 &  3.554 &  0.308 &  3.020 &  2.272 &  0.466 &  2.694 &  1.108 &  3.806 \\
3 &  0.561 &  1.188 &  1.838 &  3.920 &  0.389 &  1.892 &  2.057 &  1.341 &  0.596 &  2.277 &  3.920 \\
4 &  1.098 &  1.515 &  2.295 &  0.339 &  0.906 &  2.797 &  2.625 &  3.208 &  1.829 &  2.953 &  3.208 \\
5 &  1.085 &  3.870 &  1.581 &  0.674 &  1.738 &  1.922 &  1.288 &  1.109 &  0.447 &  0.788 &  3.870 \\
6 &  1.640 &  2.121 &  3.930 &  0.601 &  1.604 &  1.854 &  3.823 &  0.804 &  1.109 &  3.437 &  3.930 \\
7 &  1.754 &  2.700 &  2.472 &  1.940 &  3.358 &  3.898 &  0.919 &  1.042 &  2.553 &  1.207 &  3.898 \\
8 &  2.965 &  1

In [95]:
maximax, strategy = maxes.max(), maxes.argmax()
print(f"{maximax=:.{3}f}")
print(f"{strategy=}")

maximax=3.988
strategy=9


In [102]:
from scipy.special import erf

Phi = lambda x: 1-erf(x/(2**0.5))/2
Phi(1.58113883)


0.5569231490129518